### ISSUE TITLE
interoperability of 6lowpan on RPi with  openlabs 802.15.4 radio

### ISSUE THREAD

**Issue by HKRS** [linux-wpan/wpan-tools#12]
Hi,
We are able to do 6lowpan unicast b/w 2 RPi setups with  openlabs 802.15.4 radio modules. 
But we are trying to have unicast b/w RPi setup and Telos B mote( Contiki Os) without RPL because of RPL is not present in 6lowpan stack of linux.

Unicast is not happening properly. Works only very few times 1:20(First time after flahsing the Telos b mote every time).

Is interoperability possible with present stack?

Procedure we followed for RPi Setup
https://github.com/RIOT-Makers/wpan-raspbian/wiki/Create-a-generic-Raspbian-image-with-6LoWPAN-support

**Comment by alexaring** [comment]
There exists a "limited" RPL implementation for storing mode aka "unstrung" but so far I know contiki has also some limitation... there exists also issues with RPL Option in HBH exthdr -> Linux will drop it without changes. There are some patches/drafts at netdev mailinglist to allow different option fields (without parsing)... but then you need to know what you doing... Also there exists currently not way to add HBH.

**Comment by darkfader** [comment]
I'm currently adding some code to unstrung for some project. I've added some OF0 code that uses neighbour state from netlink (doing a ping when it sees a new neighbour) so it can select at least a parent that can respond (a bit). Really need to have some ETX.
It also missed some basic configuration options (with intervals/lifetimes etc.).
Anyways, I don't think interoperability is applicable to wpan-tools, since it's just the configuration tools, right?

**Comment by alexaring** [comment]
I close this as well, things to check to work with Contiki are:

Check if max allowed HBH type is correctly set in the Linux kernel sysfs or check that this Contiki specific duty cycle algorithm is disabled.
